// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykcxs6EV-1r8TF59Mctk3XHImwrkZlMw',
    appId: '1:41236243616:web:3893167c39c285fd1095c5',
    messagingSenderId: '41236243616',
    projectId: 'zello-e-commerce-80fd0',
    authDomain: 'zello-e-commerce-80fd0.firebaseapp.com',
    storageBucket: 'zello-e-commerce-80fd0.firebasestorage.app',
    measurementId: 'G-VT5Q71JK74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdicOoEGJJ7iAmvm4f4xU_EvHCOuclI3A',
    appId: '1:41236243616:android:58982606ffa1cbfd1095c5',
    messagingSenderId: '41236243616',
    projectId: 'zello-e-commerce-80fd0',
    storageBucket: 'zello-e-commerce-80fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMob7ZpXDMRgYN6_MjP4J1-72gODR5wgE',
    appId: '1:41236243616:ios:0ffe1561c5867da51095c5',
    messagingSenderId: '41236243616',
    projectId: 'zello-e-commerce-80fd0',
    storageBucket: 'zello-e-commerce-80fd0.firebasestorage.app',
    iosBundleId: 'com.example.zello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMob7ZpXDMRgYN6_MjP4J1-72gODR5wgE',
    appId: '1:41236243616:ios:0ffe1561c5867da51095c5',
    messagingSenderId: '41236243616',
    projectId: 'zello-e-commerce-80fd0',
    storageBucket: 'zello-e-commerce-80fd0.firebasestorage.app',
    iosBundleId: 'com.example.zello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDykcxs6EV-1r8TF59Mctk3XHImwrkZlMw',
    appId: '1:41236243616:web:d35997d2dc2837a61095c5',
    messagingSenderId: '41236243616',
    projectId: 'zello-e-commerce-80fd0',
    authDomain: 'zello-e-commerce-80fd0.firebaseapp.com',
    storageBucket: 'zello-e-commerce-80fd0.firebasestorage.app',
    measurementId: 'G-5WBZ2RGVM3',
  );
}
